"""baseline_migration

Revision ID: 000000000000
Revises: 1d293ffb2569
Create Date: 2026-07-04 13:34:20.221733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000000000000'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_models',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_code'), 'organizations', ['code'], unique=True)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('organization_id', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('inspections_today', sa.Integer(), nullable=False),
    sa.Column('pending_reviews', sa.Integer(), nullable=False),
    sa.Column('fraud_cases', sa.Integer(), nullable=False),
    sa.Column('approval_rate', sa.Float(), nullable=False),
    sa.Column('fraud_rate', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('gold_value_today', sa.Integer(), nullable=False),
    sa.Column('gold_processed_kg', sa.Float(), nullable=False),
    sa.Column('avg_purity', sa.String(length=10), nullable=False),
    sa.Column('map_x', sa.Float(), nullable=False),
    sa.Column('map_y', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_bank_name'), 'branches', ['bank_name'], unique=False)
    op.create_index(op.f('ix_branches_id'), 'branches', ['id'], unique=False)
    op.create_index(op.f('ix_branches_name'), 'branches', ['name'], unique=True)
    op.create_index(op.f('ix_branches_organization_id'), 'branches', ['organization_id'], unique=False)
    op.create_index(op.f('ix_branches_region'), 'branches', ['region'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('organization_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_bank_name'), 'customers', ['bank_name'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_index(op.f('ix_customers_organization_id'), 'customers', ['organization_id'], unique=False)
    op.create_index(op.f('ix_customers_status'), 'customers', ['status'], unique=False)
    op.create_table('branch_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.String(length=50), nullable=False),
    sa.Column('total_inspections', sa.Integer(), nullable=False),
    sa.Column('fraud_cases', sa.Integer(), nullable=False),
    sa.Column('approval_rate', sa.Float(), nullable=False),
    sa.Column('portfolio_value', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branch_metrics_branch_id'), 'branch_metrics', ['branch_id'], unique=False)
    op.create_table('customer_loan_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('loan_number', sa.String(length=50), nullable=False),
    sa.Column('loan_amount', sa.Float(), nullable=False),
    sa.Column('loan_status', sa.String(length=50), nullable=False),
    sa.Column('loan_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_loan_history_customer_id'), 'customer_loan_history', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_loan_history_loan_number'), 'customer_loan_history', ['loan_number'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('branch_id', sa.String(length=50), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('file_url', sa.String(length=255), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('organization_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_bank_name'), 'reports', ['bank_name'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_organization_id'), 'reports', ['organization_id'], unique=False)
    op.create_index(op.f('ix_reports_type'), 'reports', ['type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('organization_id', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('branch_id', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_region'), 'users', ['region'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.String(length=50), nullable=True),
    sa.Column('actor_name', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('organization_id', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_bank_name'), 'audit_logs', ['bank_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('drafts',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('draft_type', sa.String(length=50), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drafts_user_id'), 'drafts', ['user_id'], unique=False)
    op.create_table('employee_performance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('total_inspections', sa.Integer(), nullable=False),
    sa.Column('approved_cases', sa.Integer(), nullable=False),
    sa.Column('flagged_cases', sa.Integer(), nullable=False),
    sa.Column('accuracy_score', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_performance_employee_id'), 'employee_performance', ['employee_id'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('appraiser_id', sa.String(length=50), nullable=False),
    sa.Column('branch_id', sa.String(length=50), nullable=False),
    sa.Column('jewelry_type', sa.String(length=50), nullable=False),
    sa.Column('purity', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('thickness', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('authenticity_score', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=False),
    sa.Column('lighting', sa.Integer(), nullable=False),
    sa.Column('focus', sa.Integer(), nullable=False),
    sa.Column('angle_coverage', sa.Integer(), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('loan', sa.JSON(), nullable=False),
    sa.Column('audit', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('escalation_stage', sa.String(length=50), nullable=True),
    sa.Column('organization_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['appraiser_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_appraiser_id'), 'inspections', ['appraiser_id'], unique=False)
    op.create_index(op.f('ix_inspections_branch_id'), 'inspections', ['branch_id'], unique=False)
    op.create_index(op.f('ix_inspections_customer_id'), 'inspections', ['customer_id'], unique=False)
    op.create_index(op.f('ix_inspections_id'), 'inspections', ['id'], unique=False)
    op.create_index(op.f('ix_inspections_organization_id'), 'inspections', ['organization_id'], unique=False)
    op.create_index(op.f('ix_inspections_status'), 'inspections', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('ai_feedback',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('inspection_id', sa.String(length=50), nullable=False),
    sa.Column('feedback_text', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_feedback_inspection_id'), 'ai_feedback', ['inspection_id'], unique=False)
    op.create_table('ai_jobs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('inspection_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_jobs_inspection_id'), 'ai_jobs', ['inspection_id'], unique=False)
    op.create_table('ai_predictions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('inspection_id', sa.String(length=50), nullable=False),
    sa.Column('prediction_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_predictions_inspection_id'), 'ai_predictions', ['inspection_id'], unique=False)
    op.create_table('escalations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('inspection_id', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('assigned_to_id', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inspection_id')
    )
    op.create_index(op.f('ix_escalations_id'), 'escalations', ['id'], unique=False)
    op.create_index(op.f('ix_escalations_stage'), 'escalations', ['stage'], unique=False)
    op.create_table('evidence_vault',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inspection_id', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=False),
    sa.Column('uploaded_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_vault_inspection_id'), 'evidence_vault', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_evidence_vault_uploaded_by'), 'evidence_vault', ['uploaded_by'], unique=False)
    op.create_table('inspection_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inspection_id', sa.String(length=50), nullable=False),
    sa.Column('image_type', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=False),
    sa.Column('uploaded_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_images_inspection_id'), 'inspection_images', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_inspection_images_uploaded_by'), 'inspection_images', ['uploaded_by'], unique=False)
    op.create_table('inspection_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inspection_id', sa.String(length=50), nullable=False),
    sa.Column('density_score', sa.Float(), nullable=False),
    sa.Column('surface_score', sa.Float(), nullable=False),
    sa.Column('reflection_score', sa.Float(), nullable=False),
    sa.Column('touchstone_score', sa.Float(), nullable=False),
    sa.Column('visual_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_results_inspection_id'), 'inspection_results', ['inspection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inspection_results_inspection_id'), table_name='inspection_results')
    op.drop_table('inspection_results')
    op.drop_index(op.f('ix_inspection_images_uploaded_by'), table_name='inspection_images')
    op.drop_index(op.f('ix_inspection_images_inspection_id'), table_name='inspection_images')
    op.drop_table('inspection_images')
    op.drop_index(op.f('ix_evidence_vault_uploaded_by'), table_name='evidence_vault')
    op.drop_index(op.f('ix_evidence_vault_inspection_id'), table_name='evidence_vault')
    op.drop_table('evidence_vault')
    op.drop_index(op.f('ix_escalations_stage'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_id'), table_name='escalations')
    op.drop_table('escalations')
    op.drop_index(op.f('ix_ai_predictions_inspection_id'), table_name='ai_predictions')
    op.drop_table('ai_predictions')
    op.drop_index(op.f('ix_ai_jobs_inspection_id'), table_name='ai_jobs')
    op.drop_table('ai_jobs')
    op.drop_index(op.f('ix_ai_feedback_inspection_id'), table_name='ai_feedback')
    op.drop_table('ai_feedback')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_inspections_status'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_organization_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_customer_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_branch_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_appraiser_id'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_employee_performance_employee_id'), table_name='employee_performance')
    op.drop_table('employee_performance')
    op.drop_index(op.f('ix_drafts_user_id'), table_name='drafts')
    op.drop_table('drafts')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_bank_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_region'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_reports_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_organization_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_bank_name'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_customer_loan_history_loan_number'), table_name='customer_loan_history')
    op.drop_index(op.f('ix_customer_loan_history_customer_id'), table_name='customer_loan_history')
    op.drop_table('customer_loan_history')
    op.drop_index(op.f('ix_branch_metrics_branch_id'), table_name='branch_metrics')
    op.drop_table('branch_metrics')
    op.drop_index(op.f('ix_customers_status'), table_name='customers')
    op.drop_index(op.f('ix_customers_organization_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_bank_name'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_branches_region'), table_name='branches')
    op.drop_index(op.f('ix_branches_organization_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_name'), table_name='branches')
    op.drop_index(op.f('ix_branches_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_bank_name'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_code'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_table('ai_models')
    # ### end Alembic commands ###
