/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InspectionNewRouteImport } from './routes/inspection.new'
import { Route as InspectionIdRouteImport } from './routes/inspection.$id'

const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionNewRoute = InspectionNewRouteImport.update({
  id: '/inspection/new',
  path: '/inspection/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionIdRoute = InspectionIdRouteImport.update({
  id: '/inspection/$id',
  path: '/inspection/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manager': typeof ManagerRoute
  '/inspection/$id': typeof InspectionIdRoute
  '/inspection/new': typeof InspectionNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manager': typeof ManagerRoute
  '/inspection/$id': typeof InspectionIdRoute
  '/inspection/new': typeof InspectionNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/manager': typeof ManagerRoute
  '/inspection/$id': typeof InspectionIdRoute
  '/inspection/new': typeof InspectionNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/manager' | '/inspection/$id' | '/inspection/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/manager' | '/inspection/$id' | '/inspection/new'
  id: '__root__' | '/' | '/manager' | '/inspection/$id' | '/inspection/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManagerRoute: typeof ManagerRoute
  InspectionIdRoute: typeof InspectionIdRoute
  InspectionNewRoute: typeof InspectionNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspection/new': {
      id: '/inspection/new'
      path: '/inspection/new'
      fullPath: '/inspection/new'
      preLoaderRoute: typeof InspectionNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspection/$id': {
      id: '/inspection/$id'
      path: '/inspection/$id'
      fullPath: '/inspection/$id'
      preLoaderRoute: typeof InspectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManagerRoute: ManagerRoute,
  InspectionIdRoute: InspectionIdRoute,
  InspectionNewRoute: InspectionNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
